version: '3'

networks:
  lan:

services:

  core1:
    image: neo4j:3.4-enterprise
    restart: always
    container_name: core-placeholder
    networks:
      - lan
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_memory_pagecache_size=10M
      - NEO4J_dbms_memory_heap_initial__size=10M
      - NEO4J_AUTH=none
      - NEO4J_dbms_mode=CORE
      # - NEO4J_causalClustering_expectedCoreClusterSize=3
      - NEO4J_causalClustering_initialDiscoveryMembers=core1:5000,core2:5000,core3:5000
      - NEO4J_dbms_connector_http_listen__address=:8001
      - NEO4J_dbms_connector_https_listen__address=:8002
      - NEO4J_dbms_connector_bolt_listen__address=:8003
    ports:
      - 8001:8001
      - 8002:8002
      - 8003:8003
  core2:
    image: neo4j:3.4-enterprise
    restart: always
    networks:
      - lan
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_memory_pagecache_size=10M
      - NEO4J_dbms_memory_heap_initial__size=10M
      - NEO4J_AUTH=neo4j/neo
      - NEO4J_dbms_mode=CORE
      # - NEO4J_causalClustering_expectedCoreClusterSize=3
      - NEO4J_causalClustering_initialDiscoveryMembers=core1:5000,core2:5000,core3:5000
      - NEO4J_dbms_connector_http_listen__address=:8004
      - NEO4J_dbms_connector_https_listen__address=:8005
      - NEO4J_dbms_connector_bolt_listen__address=:8006
    ports:
      - 8004:8004
      - 8005:8005
      - 8006:8006
  core3:
    image: neo4j:3.4-enterprise
    restart: always
    networks:
      - lan
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_memory_pagecache_size=10M
      - NEO4J_dbms_memory_heap_initial__size=10M
      - NEO4J_AUTH=neo4j/neo
      - NEO4J_dbms_mode=CORE
      # - NEO4J_causalClustering_expectedCoreClusterSize=3
      - NEO4J_causalClustering_initialDiscoveryMembers=core1:5000,core2:5000,core3:5000
      - NEO4J_dbms_connector_http_listen__address=:8007
      - NEO4J_dbms_connector_https_listen__address=:8008
      - NEO4J_dbms_connector_bolt_listen__address=:8009
    ports:
      - 8007:8007
      - 8008:8008
      - 8009:8009
  readreplica1:
    image: neo4j:3.4-enterprise
    restart: always
    container_name: read-placeholder
    networks:
      - lan
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_memory_pagecache_size=10M
      - NEO4J_dbms_memory_heap_initial__size=10M
      - NEO4J_AUTH=neo4j/neo
      - NEO4J_dbms_mode=READ_REPLICA
      - NEO4J_causalClustering_initialDiscoveryMembers=core1:5000,core2:5000,core3:5000
      - NEO4J_dbms_connector_http_listen__address=:8010
      - NEO4J_dbms_connector_https_listen__address=:8011
      - NEO4J_dbms_connector_bolt_listen__address=:8012
    ports:
      - 8010:8010
      - 8011:8011
      - 8012:8012