version: '3'
networks:
  lan:
services:
  neo4jcore1:
    image: neo4j:3.4-enterprise
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_mode=CORE
      - NEO4J_causal__clustering.minimum_core_cluster_size_at_formation=3
      # - NEO4J_causal__clustering_discovery__advertised__address=neo4jcore1:5001
      - NEO4J_causal__clustering_initial__discovery__members=neo4jcore1:5000,neo4jcore2:5000,neo4jcore3:5000
      # - NEO4J_causal__clustering_discovery__advertised__address=neo4jcore1:5000
      # - NEO4J_causal__clustering_transaction__advertised__address=neo4jcore1:6000
      # - NEO4J_causal__clustering_raft__advertised__address=neo4jcore1:7000
      # - NEO4J_dbms_connectors_default__advertised__address=0.0.0.0
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports: 
      - 8001:7474
      - 8002:7473
      - 8003:7687
    deploy:
        replicas: 1
        resources:
          limits:
            memory: 500M
        restart_policy:
          condition: on-failure
    networks:
      - lan
  neo4jcore2:
    image: neo4j:3.4-enterprise
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_mode=CORE
      - NEO4J_causal_clustering.minimum_core_cluster_size_at_formation=3
      # - NEO4J_causal__clustering_discovery__advertised__address=neo4jcore1:5002
      - NEO4J_causal__clustering_initial__discovery__members=neo4jcore1:5000,neo4jcore2:5000,neo4jcore3:5000
      # - NEO4J_causal__clustering_discovery__advertised__address=neo4jcore2:5000
      # - NEO4J_causal__clustering_transaction__advertised__address=neo4jcore2:6000
      # - NEO4J_causal__clustering_raft__advertised__address=neo4jcore2:7000
      # - NEO4J_dbms_connectors_default__advertised__address=0.0.0.0
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports: 
      - 8004:7474
      - 8005:7473
      - 8006:7687
    deploy:
        replicas: 1
        resources:
          limits:
            memory: 500M
        restart_policy:
          condition: on-failure
    networks:
      - lan
  neo4jcore3:
    image: neo4j:3.4-enterprise
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_mode=CORE
      - NEO4J_causal_clustering.minimum_core_cluster_size_at_formation=3
      # - NEO4J_causal__clustering_discovery__advertised__address=neo4jcore1:5003
      - NEO4J_causal__clustering_initial__discovery__members=neo4jcore1:5000,neo4jcore2:5000,neo4jcore3:5000
      # - NEO4J_causal__clustering_discovery__advertised__address=neo4jcore3:5000
      # - NEO4J_causal__clustering_transaction__advertised__address=neo4jcore3:6000
      # - NEO4J_causal__clustering_raft__advertised__address=neo4jcore3:7000
      # - NEO4J_dbms_connectors_default__advertised__address=0.0.0.0
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports: 
      - 8007:7474
      - 8008:7473
      - 8009:7687
    deploy:
        replicas: 1
        resources:
          limits:
            memory: 500M
        restart_policy:
          condition: on-failure
    networks:
      - lan