version: '3.3'

services:
  neo-1:
    image: neo4j:3.3.4-enterprise
    volumes:
      - neo-data:/data
      - neo-logs:/var/lib/neo4j/logs
    environment:
      - NEO4J_AUTH=neo4j/blah
      - NEO4J_causalClustering_discoveryAdvertisedAddress=neo-1:5000
      - NEO4J_causalClustering_transactionAdvertisedAddress=neo-1:6000
      - NEO4J_causalClustering_raftAdvertisedAddress=neo-1:7000
      - NEO4J_causalClustering_expectedCoreClusterSize=3
      - NEO4J_causalClustering_initialDiscoveryMembers=neo-1:5000,neo-2:5000,neo-3:5000
      - NEO4J_dbms_connectors_default__advertised__address=neo-1
      - NEO4J_dbms_connector_bolt_advertised__address=:7687
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_mode=CORE

    deploy:
      mode: global
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.neodb == 1
    networks:
      - neonet

  neo-2:
    image: neo4j:3.3.4-enterprise
    volumes:
      - neo-data:/data
      - neo-logs:/var/lib/neo4j/logs
    environment:
      - NEO4J_AUTH=neo4j/blah
      - NEO4J_causalClustering_discoveryAdvertisedAddress=neo-2:5000
      - NEO4J_causalClustering_transactionAdvertisedAddress=neo-2:6000
      - NEO4J_causalClustering_raftAdvertisedAddress=neo-2:7000
      - NEO4J_causalClustering_expectedCoreClusterSize=3
      - NEO4J_causalClustering_initialDiscoveryMembers=neo-1:5000,neo-2:5000,neo-3:5000
      - NEO4J_dbms_connectors_default__advertised__address=neo-2
      - NEO4J_dbms_connector_bolt_advertised__address=:7687
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_mode=CORE

    deploy:
      mode: global
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.neodb == 2
    networks:
      - neonet

  neo-3:
    image: neo4j:3.3.4-enterprise
    volumes:
      - neo-data:/data
      - neo-logs:/var/lib/neo4j/logs
    environment:
      - NEO4J_AUTH=neo4j/blah
      - NEO4J_causalClustering_discoveryAdvertisedAddress=neo-3:5000
      - NEO4J_causalClustering_transactionAdvertisedAddress=neo-3:6000
      - NEO4J_causalClustering_raftAdvertisedAddress=neo-3:7000
      - NEO4J_causalClustering_expectedCoreClusterSize=3
      - NEO4J_causalClustering_initialDiscoveryMembers=neo-1:5000,neo-2:5000,neo-3:5000
      - NEO4J_dbms_connectors_default__advertised__address=neo-3
      - NEO4J_dbms_connector_bolt_advertised__address=:7687
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_mode=CORE

    deploy:
      mode: global
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.neodb == 3
    networks:
      - neonet

networks:
  neonet:
    driver: overlay

volumes:
  neo-data:
  neo-logs: