version: '3.3'

networks:
  elk:

volumes:
  elk-data:

services:
  elk:
    image: sebp/elk
    volumes: 
      - elk-data:/var/lib/elasticsearch
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    environment:
      - MAX_MAP_COUNT=262144
    deploy: 
      replicas: 1
      resources: 
        limits: 
          memory: 3024M
      restart_policy:
          condition: on-failure
